AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Processes incoming AWS Cost and Usage Reports and gets them ready for analysis in Athena and QuickSight
Parameters:
  
  StackTag:
    Description: "Value of the 'stack' tag"
    Type: String
    Default: "cur-processor"

  BucketName:
    Description: The name of the bucket that we will use for the reporting.
    Type: String

  ReportPathPrefix:
    Description: The path prefix that will be used for the AWS Report delivery.
    Type: String
    Default: aws-reports

  CloudWatchRetention:
    Description: "The number of days that we will store the AWS CloudWatch Logs"
    Type: String
    Default: 7

  CreateLogGroups:
    Description: "Create LogGroups so that you have control over the LogRetention"
    Type: String
    Default: "Enabled"
    AllowedValues: [ "Disabled", "Enabled" ]

  AccessKey:
    Description: "<aws-iam-key-id-(only-used-in-cross-account-scenarios)>"
    Type: String
    Default: ""
    
  SecretAccessKey:
    Description: "<secret-access-key-(only-used-in-cross-account-scenarios)>"
    NoEcho: true
    Type: String
    Default: ""

Conditions:
  LogGroupsEnabled: !Equals [!Ref CreateLogGroups, 'Enabled']

Resources:

  CostUsageReportTopic:
    Type: AWS::SNS::Topic


  StepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: !Sub states.${AWS::Region}.amazonaws.com
      Policies:
        - PolicyName: InvokeLambdaFunctions
          PolicyDocument:
            Statement:
              - Effect: Allow
                Resource:
                  - !GetAtt ProcessCostUsageFunction.Arn
                  - !GetAtt CreateAthenaResourcesFunction.Arn
                  - !GetAtt UpdateMetadataFunction.Arn
                  - !GetAtt InitializeAthenaQueriesFunction.Arn
                Action:
                  - lambda:InvokeFunction

  PrepareCurAthenaStepFunction:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub '${AWS::StackName}-PrepareCurAthenaxAcct'
      RoleArn: !GetAtt StepFunctionsRole.Arn
      DefinitionString: !Sub |
          {
            "Comment": "Process AWS Cost and Usage reports and prepare them for Athena.",
            "StartAt": "ProcessCostUsageReport",
            "States": {
              "ProcessCostUsageReport": {
                "Type": "Task",
                "Resource": "${ProcessCostUsageFunction.Arn}",
                "Next": "CreateAthenaResources"
              },
              "CreateAthenaResources": {
                "Type": "Task",
                "Resource": "${CreateAthenaResourcesFunction.Arn}",
                "Next": "UpdateMetadata"
              },
              "UpdateMetadata": {
                "Type" : "Task",
                "Resource": "${UpdateMetadataFunction.Arn}",
                "Next": "InitializeAthenaQueries"
              },
              "InitializeAthenaQueries": {
                "Type" : "Task",
                "Resource": "${InitializeAthenaQueriesFunction.Arn}",
                "End": true
              }
            }
          }

  xAcctStepFunctionStarterLogGroup:
    Condition: LogGroupsEnabled
    Type: AWS::Logs::LogGroup
    DependsOn: [ xAcctStepFunctionStarter ]
    Properties:
      LogGroupName: !Sub /aws/lambda/${xAcctStepFunctionStarter}
      RetentionInDays: !Ref CloudWatchRetention

  xAcctStepFunctionStarter:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/xacct-step-function-starter.handler
      Runtime: python2.7
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSStepFunctionsFullAccess
        - AmazonSNSFullAccess
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
        - AWSXrayFullAccess
        - Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - 'iam:PassRole'
              - 'iam:AssumeRole'
            Resource: '*'
      Timeout: 120
      MemorySize: 512
      CodeUri: ../
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
      Environment:
        Variables:
          ATHENA_BASE_OUTPUT_S3_BUCKET: !Sub s3://${BucketName}/athena
          CUR_PROCESSOR_DEST_S3_BUCKET: !Ref BucketName
          CUR_PROCESSOR_DEST_S3_PREFIX: !Ref ReportPathPrefix
          AWS_ACCOUNT_METADATA_DDB_TABLE: !Ref AWSAccountMetadata
          STEP_FUNCTION_PREPARE_CUR_ATHENA: !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${AWS::StackName}-PrepareCurAthenaxAcct
          SNS_TOPIC: !Ref CostUsageReportTopic
          LAMBDA_OWNER_AWS_ACCESS_KEY_ID: !Ref AccessKey
          LAMBDA_OWNER_AWS_SECRET_ACCESS_KEY: !Ref SecretAccessKey
      Tracing: Active
      Tags:
        stack: !Ref StackTag

  ProcessCostUsageFunctionLogGroup:
    Condition: LogGroupsEnabled
    Type: AWS::Logs::LogGroup
    DependsOn: [ ProcessCostUsageFunction ]
    Properties:
      LogGroupName: !Sub /aws/lambda/${ProcessCostUsageFunction}
      RetentionInDays: !Ref CloudWatchRetention

  ProcessCostUsageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/process-cur.handler
      Runtime: python2.7
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
        - AWSXrayFullAccess
      Timeout: 300
      MemorySize: 1536
      CodeUri: ../
      Environment:
        Variables:
          ATHENA_BASE_OUTPUT_S3_BUCKET: !Sub s3://${BucketName}/athena
          CUR_PROCESSOR_DEST_S3_BUCKET: !Ref BucketName
          CUR_PROCESSOR_DEST_S3_PREFIX: !Ref ReportPathPrefix
          AWS_ACCOUNT_METADATA_DDB_TABLE: !Ref AWSAccountMetadata
          STEP_FUNCTION_PREPARE_CUR_ATHENA: !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${AWS::StackName}-PrepareCurAthenaxAcct
          SNS_TOPIC: !Ref CostUsageReportTopic
          LAMBDA_OWNER_AWS_ACCESS_KEY_ID: !Ref AccessKey
          LAMBDA_OWNER_AWS_SECRET_ACCESS_KEY: !Ref SecretAccessKey
      Tracing: Active
      Tags:
        stack: !Ref StackTag

  CreateAthenaResourcesFunctionLogGroup:
    Condition: LogGroupsEnabled
    Type: AWS::Logs::LogGroup
    DependsOn: [ CreateAthenaResourcesFunction ]
    Properties:
      LogGroupName: !Sub /aws/lambda/${CreateAthenaResourcesFunction}
      RetentionInDays: !Ref CloudWatchRetention

  CreateAthenaResourcesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/create-athena-resources.handler
      Runtime: python2.7
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
        - AmazonAthenaFullAccess
        - AmazonDynamoDBFullAccess
        - AWSXrayFullAccess
      Timeout: 300
      MemorySize: 1536
      CodeUri: ../
      Environment:
        Variables:
          ATHENA_BASE_OUTPUT_S3_BUCKET: !Sub s3://${BucketName}/athena
          CUR_PROCESSOR_DEST_S3_BUCKET: !Ref BucketName
          CUR_PROCESSOR_DEST_S3_PREFIX: !Ref ReportPathPrefix
          AWS_ACCOUNT_METADATA_DDB_TABLE: !Ref AWSAccountMetadata
          STEP_FUNCTION_PREPARE_CUR_ATHENA: !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${AWS::StackName}-PrepareCurAthenaxAcct
          SNS_TOPIC: !Ref CostUsageReportTopic
          LAMBDA_OWNER_AWS_ACCESS_KEY_ID: !Ref AccessKey
          LAMBDA_OWNER_AWS_SECRET_ACCESS_KEY: !Ref SecretAccessKey
      Tracing: Active
      Tags:
        stack: !Ref StackTag

  InitializeAthenaQueriesFunctionLogGroup:
    Condition: LogGroupsEnabled
    Type: AWS::Logs::LogGroup
    DependsOn: [ InitializeAthenaQueriesFunction ]
    Properties:
      LogGroupName: !Sub /aws/lambda/${InitializeAthenaQueriesFunction}
      RetentionInDays: !Ref CloudWatchRetention

  InitializeAthenaQueriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/init-athena-queries.handler
      Runtime: python2.7
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
        - AmazonAthenaFullAccess
        - AmazonDynamoDBFullAccess
        - AWSXrayFullAccess
      Timeout: 300
      MemorySize: 1536
      CodeUri: ../
      Environment:
        Variables:
          ATHENA_BASE_OUTPUT_S3_BUCKET: !Sub s3://${BucketName}/athena
          CUR_PROCESSOR_DEST_S3_BUCKET: !Ref BucketName
          CUR_PROCESSOR_DEST_S3_PREFIX: !Ref ReportPathPrefix
          AWS_ACCOUNT_METADATA_DDB_TABLE: !Ref AWSAccountMetadata
          STEP_FUNCTION_PREPARE_CUR_ATHENA: !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${AWS::StackName}-PrepareCurAthenaxAcct
          SNS_TOPIC: !Ref CostUsageReportTopic
          LAMBDA_OWNER_AWS_ACCESS_KEY_ID: !Ref AccessKey
          LAMBDA_OWNER_AWS_SECRET_ACCESS_KEY: !Ref SecretAccessKey
      Tracing: Active
      Tags:
        stack: !Ref StackTag

  UpdateMetadataFunctionLogGroup:
    Condition: LogGroupsEnabled
    Type: AWS::Logs::LogGroup
    DependsOn: [ UpdateMetadataFunction ]
    Properties:
      LogGroupName: !Sub /aws/lambda/${UpdateMetadataFunction}
      RetentionInDays: !Ref CloudWatchRetention

  UpdateMetadataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/update-metadata.handler
      Runtime: python2.7
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - AWSXrayFullAccess
      Timeout: 30
      MemorySize: 256
      CodeUri: ../
      Environment:
        Variables:
          ATHENA_BASE_OUTPUT_S3_BUCKET: !Sub s3://${BucketName}/athena
          CUR_PROCESSOR_DEST_S3_BUCKET: !Ref BucketName
          CUR_PROCESSOR_DEST_S3_PREFIX: !Ref ReportPathPrefix
          AWS_ACCOUNT_METADATA_DDB_TABLE: !Ref AWSAccountMetadata
          STEP_FUNCTION_PREPARE_CUR_ATHENA: !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${AWS::StackName}-PrepareCurAthenaxAcct
          SNS_TOPIC: !Ref CostUsageReportTopic
          LAMBDA_OWNER_AWS_ACCESS_KEY_ID: !Ref AccessKey
          LAMBDA_OWNER_AWS_SECRET_ACCESS_KEY: !Ref SecretAccessKey
      Tracing: Active
      Tags:
        stack: !Ref StackTag

  AWSAccountMetadata:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: awsPayerAccountId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5


Outputs:
  xAcctStepFunctionStarterFunction:
    Description: Lambda function that starts Step Function for processing CUR for other AWS accounts
    Value: !Ref xAcctStepFunctionStarter
    Export:
      Name: !Sub "${AWS::StackName}-xAcctStepFunctionStarterFunction"

  CreateAthenaResourcesFunctionOutput:
    Description: Lambda function that creates Athena databasees and tables when processing CUR.
    Value: !Ref CreateAthenaResourcesFunction
    Export:
      Name: !Sub "${AWS::StackName}-CreateAthenaResourcesFunction"


  InitializeAthenaQueriesFunctionOutput:
    Description: Lambda function that initializes Athena queries, so that they can be accessed by the API from S3 and Athena doesn't need to be queried al the time.
    Value: !Ref InitializeAthenaQueriesFunction
    Export:
      Name: !Sub "${AWS::StackName}-InitializeAthenaQueriesFunction"



  PrepareCurAthenaStepFunctionArn:
    Description: Step Function that processes Cost and Usage Reports for Athena
    Value: !Ref PrepareCurAthenaStepFunction
    Export:
      Name: !Sub "${AWS::StackName}-PrepareCurAthenaStepFunctionArn"


  BucketName:
    Description: The S3 Bucket name that must be used for the AWS Report delivery.
    Value: !Ref BucketName

  ReportPathPrefix:
    Description: The path prefix that must be used for the AWS Report delivery.
    Value: !Ref ReportPathPrefix
